name: Version Bump and Tag

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Bump version
      id: bump_version
      run: |
        poetry version patch
        VERSION=$(poetry version -s)
        echo "new_version=$VERSION" >> $GITHUB_ENV

    - name: Commit and push version bump
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -am "Bump version to ${{ env.new_version }}"
        git push origin main

    - name: Create new tag
      run: |
        VERSION=${{ env.new_version }}
        git tag "v$VERSION"
        git push origin "v$VERSION"
